name: Pages Me
run-name: ${{ github.actor }} GitHub Actions Pages Me

#on: [push]

on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - main
jobs:

  Action-Pages-Me-job:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18.13'
      - run: npm install -g bats
      - run: bats -v
      - run: ls
      #rm /var/www/html/Z-Anatomy/docs/ -Rf ;cd /var/www/html/Z-Anatomy/WEBSITE/ ;ng build --output-path /var/www/html/Z-Anatomy/docs/ --base-href Z-Anatomy --verbose ; cd /var/www/html/Z-Anatomy/
      - run: rm dist/ -Rf ; rm docs/ -Rf ;

      #from https://blog.khophi.co/deploy-angular-with-github-actions/
      - run: cd WEBSITE ; npm install
      - run: cd WEBSITE ; npm install -g @angular/cli > /dev/null
      - run: cd WEBSITE ; ng build 


      - run: cd WEBSITE/;sudo npm install; #incremental
      - run: cd WEBSITE/;sudo npm install; sudo npm install -g  ; ls; ng build
      - run: cd WEBSITE/;npm install; npm install -g  ; ls; ng build --base-href "z-anatomy"; cp dist -Rf ../docs #https://stackoverflow.com/questions/46623571/angular-ng-command-not-found

      #- run: cd WEBSITE/; ls; ng build --output-path ../docs/ --base-href Z-Anatomy --verbose 

      - run: ls docs

