name: Pages Me
run-name: ${{ github.actor }} GitHub Actions Pages Me

#on: [push]

on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - main
jobs:

  Action-Pages-Me-job:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - run: ls
      #rm /var/www/html/Z-Anatomy/docs/ -Rf ;cd /var/www/html/Z-Anatomy/WEBSITE/ ;ng build --output-path /var/www/html/Z-Anatomy/docs/ --base-href Z-Anatomy --verbose ; cd /var/www/html/Z-Anatomy/
      - run: rm docs/ -Rf

      - run: npm install -g @angular/cli@15.2.10 #https://stackoverflow.com/questions/46623571/angular-ng-command-not-found
      #- run: cd WEBSITE/; ls; ng build --output-path ../docs/ --base-href Z-Anatomy --verbose
      - run: cd WEBSITE/; ls; ng build ; cp dist -Rf ../docs
      - run: ls docs

